nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-berry.js
checksumBehavior: update

packageExtensions:
    'aws-cdk@*':
        dependencies:
            'aws-cdk-lib': '2.137.0'
            'aws-sdk-mock': '5.6.0'
            'axios': '^1.6.7'
            'constructs': '^10.0.0'
            'fast-check': '^3.15.1'
            'madge': '^5.0.2'
            'make-runnable': '^1.4.1'
            'nock': '^13.5.3'
            'sinon': '^9.2.4'
            'ts-mock-imports': '^1.3.8'
            'xml-js': '^1.6.11'
            '@aws-cdk/cloud-assembly-schema': '2.137.0'
            '@aws-cdk/cloudformation-diff': '2.137.0'
            '@aws-cdk/cx-api': '2.137.0'
            '@aws-cdk/region-info': '2.137.0'
            '@jsii/check-node': '1.94.0'
            'archiver': '^5.3.2'
            'aws-sdk': '^2.1562.0'
            'camelcase': '^6.3.0'
            'cdk-assets': '2.137.0'
            'cdk-from-cfn': '^0.133.0'
            'chalk': '^4'
            'chokidar': '^3.6.0'
            'decamelize': '^5.0.1'
            'fs-extra': '^9.1.0'
            'glob': '^7.2.3'
            'json-diff': '^0.10.0'
            'minimatch': '^9.0.3'
            'promptly': '^3.2.0'
            'proxy-agent': '^6.4.0'
            'semver': '^7.6.0'
            'source-map-support': '^0.5.21'
            'strip-ansi': '^6.0.1'
            'table': '^6.8.1'
            'uuid': '^8.3.2'
            'wrap-ansi': '^7.0.0'
            'yaml': '1.10.2'
            'yargs': '^16.2.0'
